# -*- mode: python ; coding: utf-8 -*-

import sys
sys.setrecursionlimit(5000)

a = Analysis(
    ['run_exe.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('backend', 'backend'),
        ('index.html', '.'),
        ('style.css', '.'),
        ('app.js', '.'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'edge_tts',
        'edge_tts.util',
    ],
    hookspath=[],
    hooksconfig={},
    excludes=[
        'gradio', 'gradio_client', 'hf_gradio',
        'spaces', 'omnivoice', 'voxcpm',
        'transformers',
        'torch', 'torchaudio', 'torchao', 'torchcodec',
        'torchdata', 'torchtune',
        'accelerate', 'safetensors',
        'tensorflow', 'tensorboardX',
        'datasets',
        'sklearn',
        'scipy',
        'pandas',
        'matplotlib',
        'numba', 'llvmlite',
        'av',
        'librosa',
        'onnxruntime',
        'ctranslate2',
        'faster_whisper',
        'PyQt6', 'PySide6', 'shiboken6', 'qtpy', 'QtAwesome',
        'pyarrow',
        'sympy',
        'mpmath',
        'moviepy',
        'pedalboard',
        'sounddevice', 'soundfile',
        'flash_attn',
        'einops', 'einx',
        'modelscope',
        'kagglehub', 'kagglesdk',
        'lancedb',
        'chromadb',
        'playwright',
        'watchfiles',
        'lxml',
        'Crypto', 'Cryptodome',
        'brotli',
        'secretstorage',
        'curl_cffi',
        'websockets',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='0xForge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)
